In [1]:
import pandas as pd

In [14]:
customerData = pd.read_csv("../dataset/kopo_customerdata.csv")

In [12]:
pwd

'C:\\Users\\Administrator\\Python_ST_EX\\dataload'

In [18]:
customerData.head(2)

,CUSTOMERCODE,STATENAME,ST,GENDER,DOB,GENDER1,EMAIL,FEST_CNT,TOTAL_AMOUNT,AC_AMOUNT,AV_AMOUNT,HA_AMOUNT,EMI_CE_AMOUNT,IS_HIGHEND,CNT_VIST,GAP_VISIT
0,1503989,State2,2,Male,0,1,1,0,30300,0,30300,0,0,0,1,0
1,1190338,State2,2,Male,0,1,0,1,46500,0,46500,0,0,0,1,0

In [24]:
amountList = customerData["TOTAL_AMOUNT"].tolist()

In [25]:
type(amountList)

list

In [26]:
len(amountList)

300000

In [34]:
type(amountList)

list

### 정렬을 이용한 평균 산출

In [35]:
amountList.sort()

In [36]:
amountList

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 600,
 600,
 700,
 800,
 800,
 900,
 900,
 900,
 900,
 1000,
 1000,
 1100,
 1100,
 1100,
 1100,
 1100,
 1100,
 1100,
 1200,
 1300,
 1300,
 1300,
 1400,
 1400,
 1400,
 1500,
 1500,
 1500,
 1500,
 1600,
 1600,
 1600,
 1600,
 1600,
 1600,
 1600,
 1600,
 1600,
 1700,
 1700,
 1700,
 1700,
 1700,
 1700,
 1800,
 1800,
 1800,
 1800,
 1800,
 1900,
 1900,
 2000,
 2000,
 2000,
 2000,
 2000,
 2000,
 2000,
 2000,
 2000,
 2000,
 2000,
 2100,
 2100,
 2100,
 2100,
 2100,
 2100,
 2100,
 2100,
 2100,
 2100,
 2100,
 2100,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2200,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2300,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2400,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 2500,
 ...]

### 최소최대값 뺀 평균 산출

In [29]:
minvalue=min(amountList)
minvalue

0

In [30]:
maxvalue=max(amountList)
maxvalue

3103500

### min, max value 삭제

In [31]:
amountList.remove(minvalue)
amountList.remove(maxvalue)

In [33]:
average=sum(amountList)/len(amountList)
average

35218.95312635417

In [37]:
tvList2 = ['UN40EN001', 'UN40EN002','UN40EN003', 'UN40EN004']

In [46]:
for i in range(0,len(tvList2)):
    print(tvList2[i])

UN40EN001
UN40EN002
UN40EN003
UN40EN004

In [47]:
tvList2 = ['UN40EN001', 'LED TV_UN40EN002','LED TV_UN40EN003', 'UN40EN004']

In [48]:
preFix = 'LED TV_'

In [80]:
for i in range(0,len(tvList2)):
    
    ## preFix 개수를 산출한다
    preFixCount=tvList2[i].count(preFix)
    preFixCount
    
    ## 만약 카운트가 0인 경우 preFix를 앞에 붙인다
    if(preFixCount == 0) : 
        tvList2[i] = preFix + tvList2[i]
        
    ## 만약 카운트가 1개인경우 그냥 유지한다
    else:
        tvList2[i] = tvList2[i]

In [81]:
tvList2

['LED TV_UN40EN001',
 'LED TV_UN40EN002',
 'LED TV_UN40EN003',
 'LED TV_UN40EN004']

In [73]:
i=0

In [74]:
## preFix 개수를 산출한다
preFixCount=tvList2[i].count(preFix)
preFixCount

0

In [75]:
preFixCount == 0

True

In [77]:
preFix

'LED TV_'

In [79]:
type([tvList2[i]])

list

In [76]:
tvList2[i] = preFix + tvList2[i]

TypeError: must be str, not list

In [ ]:
## preFix 개수를 산출한다
preFixCount=tvList2[i].count(preFix)
preFixCount

## 만약 카운트가 0인 경우 preFix를 앞에 붙인다
if(preFixCount == 0) : 
    tvList2[i] = preFix + [tvList2[i]]

## 만약 카운트가 1개인경우 그냥 유지한다
else:
    tvList2[i] = tvList2[i]

In [60]:
tvList2

['UN40EN001', 'LED TV_UN40EN002', 'LED TV_UN40EN003', 'UN40EN004']

In [67]:
def roundTwo(value):
    step1 = value*100
    step2 = round(step1)
    step3 = step2/100
    return step3

a=10
b=5.3
display2Digit = a/b
answer = roundTwo(display2Digit)
answer

1.89

In [83]:
inputList=[10,100,200,1000,1,2]

In [90]:
def listAverage(inputList):
    # inputList=[10,100,200,1000,1,2]

    minvalue = min(inputList)
    maxvalue = max(inputList)

    inputList.remove(minvalue)
    inputList.remove(maxvalue)

    average = sum(inputList) / len(inputList)
    
    return average

In [87]:
average

218.83333333333334

In [94]:
listA = [1,2,3,4,5,6,7]
listB = [2,2,3,4,5,6,6]
listC = [3,2,3,4,5,5,6]
listD = [4,2,3,4,5,6,7]

In [95]:
listAverage(listA)

4.0

In [96]:
listAverage(listB)

4.0

In [112]:
# PANDAS 패키지불러오기
import pandas as pd
import pymysql from sqlalchemy
import create_engine

# DB 커넥션열기
engine = create_engine('mysql+pymysql://kopo:kopo@13.209.112.251:3306/kopo')

# DB 테이블을읽어 Data Frame 변수에저장하기

selloutData = pd.read_sql_query('SELECT * FROM kopo_product_volume', engine) 
selloutData.head(1)

SyntaxError: invalid syntax (<ipython-input-112-82a4a648f018>, line 3)

In [107]:
# 컬럼해더재정의
selloutData.columns = ['REGIONID','PRODUCTGROUP','YEARWEEK','VOLUME']

# 데이터저장
resultname='mysqlresult_ym'
selloutData.to_sql(resultname, engine, if_exists='replace')

NameError: name 'selloutData' is not defined

In [118]:
cutomerData=pd.read_csv("../dataset/customerdata.csv")

In [119]:
customerData

     CUSTID  AVERAGEPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0    A13566   4273.900000    3          6.4    1.679181  Big-Screen-lover
1    A14219   3642.441950    2          4.0    2.682023      Sleeping-dog
2    A15312   3653.884565    2          5.0    3.208202      Sleeping-dog
3    A16605   3713.211107    2          6.6    0.900000        Early-bird
4    B10634   3391.074215    2          4.2    2.453656      Sleeping-dog
5    B16849   3755.263391    2          4.7    2.786665      Sleeping-dog
6    B18816   3213.911446    2          6.4    0.900000        Early-bird
7    C10639   3516.500000    2          5.2    2.564830  Big-Screen-lover
8    C12717   3732.900000    2          5.7    2.069995  Big-Screen-lover
9    C15050   4020.173425    2          4.9    3.013440      Sleeping-dog
10   C18306   4005.005142    2          4.7    3.113618      Sleeping-dog
11   C18622   3246.000000    1          5.0    1.891624  Big-Screen-lover
12   C19178   3624.700000    2          5.6    2.137246  Big-Screen-lover
13   D11795   2991.014703    2          6.4    0.800000        Early-bird
14   D13030   3227.855655    2          4.8    3.467370      Sleeping-dog
15   D15289   4165.700000    2          6.9    2.911016  Big-Screen-lover
16   D17241   4166.533130    2          4.7    2.577757      Sleeping-dog
17   D17880   3383.145853    2          4.5    2.903990      Sleeping-dog
18   E10778   4165.700000    2          6.7    2.122257  Big-Screen-lover
19   E11917   3516.500000    2          5.5    2.087540  Big-Screen-lover
20   E16075   3418.048887    2          4.2    2.771469      Sleeping-dog
21   E16221   3408.300000    2          5.0    1.988682  Big-Screen-lover
22   E18145   3408.300000    2          4.9    1.521029  Big-Screen-lover
23   E19404   3764.940414    2          6.5    0.900000        Early-bird
24   F10222   3191.065822    2          6.5    0.900000        Early-bird
25   F12979   4165.700000    2          6.1    2.128362  Big-Screen-lover
26   F14866   3137.800000    2          5.1    1.725892  Big-Screen-lover
27   F17131   3179.708359    3          6.5    1.100000        Early-bird
28   F18646   3334.244233    2          4.5    3.273196      Sleeping-dog
29   F19938   3732.900000    2          5.4    2.011303  Big-Screen-lover
..      ...           ...  ...          ...         ...               ...
120  U16894   3234.465609    2          3.6    2.606419      Sleeping-dog
121  U17547   3313.905655    2          4.0    2.448368      Sleeping-dog
122  U17748   3394.152840    2          4.0    2.185742      Sleeping-dog
123  V10654   3902.329790    2          4.6    3.260149      Sleeping-dog
124  V16516   3149.259875    2          4.1    2.410823      Sleeping-dog
125  V16704   2605.631083    2          6.6    0.900000        Early-bird
126  V18566   3527.701867    3          6.5    0.900000        Early-bird
127  V19072   3462.400000    2          5.3    1.922932  Big-Screen-lover
128  W10832   3527.360507    2          4.1    2.136971      Sleeping-dog
129  W13032   4003.400000    2          6.1    2.519623  Big-Screen-lover
130  W13404   4296.873743    3          6.5    1.100000        Early-bird
131  W13995   2411.008838    2          6.4    1.000000        Early-bird
132  W16193   3402.729703    2          6.4    0.900000        Early-bird
133  W18228   3480.455474    2          6.4    0.900000        Early-bird
134  X10158   3949.300000    2          6.3    1.815666  Big-Screen-lover
135  X13390   2947.543982    3          6.3    1.100000        Early-bird
136  X14259   3481.314549    2          4.3    2.528063      Sleeping-dog
137  X19598   3516.500000    2          5.1    2.646259  Big-Screen-lover
138  X19768   3486.085831    2          4.6    2.835355      Sleeping-dog
139  Y10906   3408.300000    2          6.0    2.131432  Big-Screen-lover
140  Y12458   2976.211190    1          3.5    2.199677      Sleeping-dog
141  Y13678   3408.300000    2          5.6    2.084005  Big-Screen-lover
142  Z11525   3259.018704    3          6.4    0.900000        Early-bird
143  Z12343   3498.896985    2          6.6    0.900000        Early-bird
144  Z12772   3029.600000    2          4.9    2.093035  Big-Screen-lover
145  Z13253   3678.800000    2          5.9    2.463670  Big-Screen-lover
146  Z13534   3662.437527    3          6.6    0.900000        Early-bird
147  Z16428   3516.500000    2          5.8    2.371301  Big-Screen-lover
148  Z16735   3300.100000    2          5.6    1.704942  Big-Screen-lover
149  Z19835   3326.526183    2          6.7    1.200000        Early-bird

[150 rows x 6 columns]

In [121]:
customerData.columns = ['CUSTID','AVGPRICE','EMI','DEVICECOUNT','PRODUCTAGE','CUSTTYPE']

## 데이터프레임생성
customerData = pd.DataFrame(customerData)

## 조건설정
answer1 = customerData[ (customerData.EMI==3) & (customerData.DEVICECOUNT>5) ]
answer2 = customerData.query('EMI == 3 & DEVICECOUNT > 5')

In [123]:
answer1

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0    A13566  4273.900000    3          6.4    1.679181  Big-Screen-lover
27   F17131  3179.708359    3          6.5    1.100000        Early-bird
33   G16437  3787.328898    3          6.7    1.000000        Early-bird
36   G18402  3402.199381    3          6.5    1.000000        Early-bird
40   H16326  3988.935304    3          6.5    0.900000        Early-bird
45   I12899  3018.895637    3          6.4    0.900000        Early-bird
51   J10809  3676.135627    3          6.5    0.800000        Early-bird
52   J15083  2811.265932    3          6.0    0.900000        Early-bird
53   J16445  3041.848186    3          6.4    0.800000        Early-bird
60   L13892  3263.515145    3          6.7    1.100000        Early-bird
67   N13273  3839.694732    3          6.9    1.100000        Early-bird
95   R16364  3592.353540    3          6.2    0.900000        Early-bird
107  S17396  3895.200000    3          6.1    2.055707  Big-Screen-lover
113  T11473  4165.700000    3          6.7    1.780674  Big-Screen-lover
126  V18566  3527.701867    3          6.5    0.900000        Early-bird
130  W13404  4296.873743    3          6.5    1.100000        Early-bird
135  X13390  2947.543982    3          6.3    1.100000        Early-bird
142  Z11525  3259.018704    3          6.4    0.900000        Early-bird
146  Z13534  3662.437527    3          6.6    0.900000        Early-bird

In [124]:
answer2

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0    A13566  4273.900000    3          6.4    1.679181  Big-Screen-lover
27   F17131  3179.708359    3          6.5    1.100000        Early-bird
33   G16437  3787.328898    3          6.7    1.000000        Early-bird
36   G18402  3402.199381    3          6.5    1.000000        Early-bird
40   H16326  3988.935304    3          6.5    0.900000        Early-bird
45   I12899  3018.895637    3          6.4    0.900000        Early-bird
51   J10809  3676.135627    3          6.5    0.800000        Early-bird
52   J15083  2811.265932    3          6.0    0.900000        Early-bird
53   J16445  3041.848186    3          6.4    0.800000        Early-bird
60   L13892  3263.515145    3          6.7    1.100000        Early-bird
67   N13273  3839.694732    3          6.9    1.100000        Early-bird
95   R16364  3592.353540    3          6.2    0.900000        Early-bird
107  S17396  3895.200000    3          6.1    2.055707  Big-Screen-lover
113  T11473  4165.700000    3          6.7    1.780674  Big-Screen-lover
126  V18566  3527.701867    3          6.5    0.900000        Early-bird
130  W13404  4296.873743    3          6.5    1.100000        Early-bird
135  X13390  2947.543982    3          6.3    1.100000        Early-bird
142  Z11525  3259.018704    3          6.4    0.900000        Early-bird
146  Z13534  3662.437527    3          6.6    0.900000        Early-bird

In [128]:
customerData = pd.read_csv("../dataset/kopo_customerdata.csv")

In [129]:
customerData

,CUSTOMERCODE,STATENAME,ST,GENDER,DOB,GENDER1,EMAIL,FEST_CNT,TOTAL_AMOUNT,AC_AMOUNT,AV_AMOUNT,HA_AMOUNT,EMI_CE_AMOUNT,IS_HIGHEND,CNT_VIST,GAP_VISIT
0,1503989,State2,2,Male,0,1,1,0,30300,0,30300,0,0,0,1,0
1,1190338,State2,2,Male,0,1,0,1,46500,0,46500,0,0,0,1,0
2,1424715,State2,2,Female,0,2,0,0,22700,0,0,22700,0,0,1,0
3,2483305,State2,2,Male,0,1,0,1,31400,0,31400,0,0,0,1,0
4,1178802,State2,2,Male,0,1,0,1,44900,0,0,44900,0,0,1,0
5,859044,State2,2,Male,0,1,0,0,38300,38300,0,0,0,0,1,0
6,734198,State2,2,Female,0,2,0,0,19900,0,0,19900,0,0,1,0
7,1443485,State2,2,Female,0,2,0,0,14800,0,0,14800,0,0,1,0
8,2340520,State2,2,Male,0,1,0,1,24400,0,0,24400,0,0,1,0
9,697949,State2,2,Male,0,1,0,1,30400,0,0,30400,0,0,1,0
10,385031,State2,2,Male,0,1,0,1,30300,0,0,30300,0,0,1,0
11,1944258,State2,2,Female,0,2,0,0,34300,0,18000,16300,0,0,1,0
12,2029521,State2,2,Female,0,2,0,0,14900,0,0,14900,0,0,1,0
13,1429192,State2,2,Male,0,1,0,0,16300,0,0,16300,0,0,1,0
14,892851,State2,2,Male,0,1,0,1,25000,0,0,25000,0,0,1,0
15,1554976,State2,2,Male,0,1,0,2,27500,0,0,27500,0,0,2,69
16,1154228,State2,2,Male,0,1,1,0,18200,0,0,18200,0,0,1,0
17,816582,State2,2,Male,0,1,0,1,40200,0,40200,0,0,0,2,940
18,675948,State2,2,Female,0,2,0,1,74600,0,0,74600,0,0,1,0
19,965940,State2,2,Male,0,1,0,0,42700,42700,0,0,0,0,1,0
20,2636314,State2,2,Male,0,1,0,0,14900,0,14900,0,0,0,1,0
21,577344,State2,2,Female,0,2,0,0,58700,0,24500,34200,0,0,2,21
22,910781,State2,2,Male,0,1,0,1,16000,0,16000,0,0,0,1,0
23,541107,State2,2,Female,0,2,0,1,17800,0,0,17800,0,0,1,0
24,1860112,State2,2,Male,0,1,0,0,26800,0,0,26800,0,0,1,0
25,1016762,State2,2,Male,1,1,0,1,14000,0,0,14000,0,0,1,0
26,2029821,State2,2,Male,0,1,0,0,31800,0,0,31800,0,0,1,0
27,765206,State2,2,Male,0,1,0,0,16000,0,0,16000,0,0,1,0
28,2174694,State2,2,Male,0,1,0,1,37600,0,0,37600,0,0,1,0
29,1196869,State2,2,Female,0,2,0,1,32800,0,16700,16100,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299970,2436525,State1,1,Male,0,1,0,1,67100,0,0,67100,0,0,1,0
299971,1238030,State1,1,Male,0,1,0,0,70100,0,55800,14300,0,0,3,663
299972,923009,State1,1,Male,0,1,0,1,17600,0,17600,0,0,0,1,0
299973,1433055,State1,1,Male,0,1,0,0,14200,0,0,14200,0,0,1,0
299974,2639022,State1,1,Male,0,1,0,0,66600,0,33000,33600,0,0,1,0
299975,1076615,State1,1,Male,0,1,0,1,35300,0,0,35300,0,0,1,0
299976,1017806,State1,1,Male,0,1,0,1,14900,0,0,14900,0,0,1,0
299977,1673649,State1,1,Male,0,1,0,2,26900,0,26900,0,0,0,2,511
299978,2304135,State1,1,Male,0,1,0,0,26300,0,26300,0,0,0,1,0
299979,726202,State1,1,Male,0,1,0,0,26300,0,26300,0,0,0,1,0
299980,2531738,State1,1,Male,0,1,0,0,13200,0,13200,0,0,0,1,0
299981,732024,State1,1,Male,0,1,0,0,13600,0,0,13600,0,0,1,0
299982,1829484,State1,1,Female,0,2,0,0,28500,0,0,28500,0,0,1,0
299983,923895,State1,1,Male,0,1,0,1,15600,0,15600,0,0,0,1,0
299984,2544242,State1,1,Male,0,1,0,0,18600,0,0,18600,0,0,1,0
299985,1006611,State1,1,Male,0,1,0,1,16500,0,0,16500,0,0,1,0
299986,1795625,State1,1,Male,0,1,0,1,18400,0,0,18400,0,0,1,0
299987,731422,State1,1,Male,0,1,0,0,14800,0,0,14800,0,0,1,0
299988,463974,State1,1,Male,0,1,0,0,20400,0,0,20400,0,0,1,0
299989,1274816,State1,1,Male,0,1,0,1,15900,0,15900,0,0,0,1,0
299990,2034458,State1,1,Male,0,1,0,0,24300,0,0,24300,0,0,1,0
299991,1349673,State1,1,Male,0,1,0,1,21200,0,0,21200,0,0,1,0
299992,1098613,State1,1,Male,0,1,0,0,14000,0,14000,0,0,0,1,0
299993,721218,State1,1,Male,0,1,0,0,31400,0,0,31400,0,0,1,0
299994,598593,State1,1,Male,0,1,0,0,29000,0,0,29000,0,0,1,0
299995,465757,State1,1,Male,0,1,0,0,40600,0,40600,0,0,0,1,0
299996,1890264,State1,1,Male,0,1,0,1,48000,48000,0,0,0,0,1,0
299997,1857537,State1,1,Female,0,2,0,0,32300,0,0,32300,0,0,1,0
299998,2209324,State1,1,Male,0,1,0,1,48500,0,48500,0,0,0,1,0
299999,1875146,State1,1,Male,0,1,0,1,16500,0,0,16500,0,0,1,0

In [131]:
customerData.columns = ['GENDER','EMAIL']

## 데이터프레임생성
customerData = pd.DataFrame(customerData)

## 조건설정
answer1 = customerData[ (customerData.GENDER==male & (customerData.EMAIL>5) ]

SyntaxError: invalid syntax (<ipython-input-131-190fac9083b0>, line 7)